### ISSUE TITLE
Chat Servers section: mostly broken links

### ISSUE THREAD

**Issue by dewf** [hisaac/macOS-Developer-Resources#9]
Just FYI, all but one (Core Intuition) in the chat section seem to be closed down (perhaps relocated?)

**Comment by hisaac** [comment]
Thanks for the heads up! I'm not really actively using or updating this, so I hadn't noticed. I'll make an update to fix this though ASAP.

**Comment by cdf1982** [comment]
FWIW, the [AppKit Abusers (Slack)](https://join.slack.com/t/appkit-abusers/shared_invite/zt-1n1q2c9px-kxI12f~1omQZDSyhO3Jr0Q) link is also broken now.

**Comment by hisaac** [comment]
Thanks for the heads up @cdf1982! Fixed in https://github.com/hisaac/macOS-Developer-Resources/pull/11.
